package ru.nsu.astakhov.autodocs.integration.google.scanner;

import lombok.Getter;
import lombok.RequiredArgsConstructor;

@RequiredArgsConstructor
@Getter
public enum InternshipColumnType {
    FULL_NAME(0),
    SPECIALIZATION(1),
    GROUP_NAME(2),
    INTERNSHIP_TYPE(3),
    THESIS_SUPERVISOR_NAME(4),
    THESIS_SUPERVISOR_POSITION(5),
    THESIS_SUPERVISOR_JOB(6),
    THESIS_SUPERVISOR_DEGREE(7),
    THESIS_SUPERVISOR_TITLE(8),
    FULL_ORGANIZATION_NAME(9),
    NSU_SUPERVISOR_NAME(10),
    NSU_SUPERVISOR_POSITION(11),
    NSU_SUPERVISOR_JOB(12),
    NSU_SUPERVISOR_DEGREE(13),
    NSU_SUPERVISOR_TITLE(14),
    ORGANIZATION_SUPERVISOR_NAME(15),
    ORGANIZATION_SUPERVISOR_POSITION(16),
    ORGANIZATION_SUPERVISOR_JOB(17),
    ORGANIZATION_SUPERVISOR_DEGREE(18),
    ORGANIZATION_SUPERVISOR_TITLE(19),
    ADMINISTRATIVE_ACT_FROM_ORGANIZATION(20),
    FULL_PLACE_OF_INTERNSHIP(21),
    ORGANIZATION_NAME(22),
    EMAIL(23),
    EDU_PROGRAM(24),
    ACTUAL_SUPERVISOR(25),
    DATE_OF_PRACTICE_ASSIGNMENT(26);

    private final int columnNumber;
}
